### ISSUE TITLE
Add trailing slash to /project route

### ISSUE THREAD

**Issue by mplewis** [teslaworksumn/teslaworks.net#21]
`@app.route('/<project>')` --> `@app.route('/<project>/')`

Makes the browser add the trailing slash too. Sweet.

**Comment by taylortrimble** [comment]
I'm guessing the reason you want to do this is because currently `http://teslaworks.net/projectname` works and `http://teslaworks.net/projectname/` throws a 404. And because if we route with the trailing slash both work?

**Comment by mplewis** [comment]
A little, but just because I like it when I go to `
teslaworks.net/audioproject` and my browser kicks me over to `
teslaworks.net/audioproject/` silently.

**Comment by taylortrimble** [comment]
I have the opposite aesthetic (prefer non-trailing URLs) like you find on Basecamp and GitHub. :stuck_out_tongue_winking_eye: But there's also this, which is why I liked non-trailing:

`/project#specific-place-on-page` vs `/project/#specific-place-on-page`

`id`s! What do you think about adding `app.url_map.strict_slashes = False` instead? Both trailing and non-trailing would work, but they'd stay the way they're typed by the user.

**Comment by mplewis** [comment]
I like that. Let's go with it.
